<?php

namespace Database\Seeders;

use App\Models\Agent;
use App\Models\Listing;
use App\Models\Location;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ListingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $listings = [
            [
                'title' => 'Elegant 4 Bedroom Detached Duplex',
                'listing_type' => 'sale',
                'property_type' => 'Detached House',
                'price' => 450000000,
                'bedrooms' => 4,
                'bathrooms' => 5,
                'toilets' => 6,
                'parking_spaces' => 2,
                'area_sqm' => 480,
                'address' => 'Bourdillon Road, Ikoyi',
                'location' => 'Ikoyi',
                'agent' => 'adaeze.okafor@summitestates.ng',
                'featured' => true,
                'description' => 'A beautifully finished 4 bedroom detached duplex with a private pool and staff quarters, minutes from the waterfront.',
            ],
            [
                'title' => 'Prime Commercial Shopping Complex',
                'listing_type' => 'sale',
                'property_type' => 'Commercial',
                'price' => 900000000,
                'bedrooms' => null,
                'bathrooms' => 4,
                'toilets' => 6,
                'parking_spaces' => 40,
                'area_sqm' => 2100,
                'address' => 'Ozumba Mbadiwe Avenue, Victoria Island',
                'location' => 'Victoria Island',
                'agent' => 'ibinabo.wokoma@harborline.ng',
                'featured' => true,
                'description' => 'A three-floor retail complex with 18 lettable units and dedicated parking, currently fully tenanted.',
            ],
            [
                'title' => '2 Bedroom Serviced Shortlet Apartment',
                'listing_type' => 'shortlet',
                'property_type' => 'Apartment',
                'price' => 85000,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'toilets' => 3,
                'parking_spaces' => 1,
                'area_sqm' => 110,
                'address' => 'Freedom Way, Lekki Phase 1',
                'location' => 'Lekki',
                'agent' => 'chiamaka.nwosu@lekkishores.ng',
                'featured' => true,
                'description' => 'Fully furnished shortlet apartment with 24-hour power, pool access, and daily housekeeping. Priced per night.',
            ],
            [
                'title' => '3 Bedroom Flat for Rent',
                'listing_type' => 'rent',
                'property_type' => 'Apartment',
                'price' => 3500000,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'toilets' => 4,
                'parking_spaces' => 2,
                'area_sqm' => 160,
                'address' => 'Adeniran Ogunsanya Street, Surulere',
                'location' => 'Surulere',
                'agent' => 'tunde.bakare@capitalliving.ng',
                'featured' => false,
                'description' => 'Spacious 3 bedroom flat in a serviced compound with backup generator and 24-hour security. Annual rent.',
            ],
            [
                'title' => '6-Bedroom Luxury Duplex with BQ',
                'listing_type' => 'sale',
                'property_type' => 'Detached House',
                'price' => 620000000,
                'bedrooms' => 6,
                'bathrooms' => 6,
                'toilets' => 7,
                'parking_spaces' => 4,
                'area_sqm' => 650,
                'address' => 'Zone A, Banana Island',
                'location' => 'Ikoyi',
                'agent' => 'adaeze.okafor@summitestates.ng',
                'featured' => true,
                'description' => 'An expansive 6 bedroom luxury duplex with two boys quarters, home cinema, and private jetty access.',
            ],
            [
                'title' => 'Serviced 1 Bedroom Apartment for Rent',
                'listing_type' => 'rent',
                'property_type' => 'Apartment',
                'price' => 1800000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'toilets' => 2,
                'parking_spaces' => 1,
                'area_sqm' => 65,
                'address' => 'Allen Avenue, Ikeja',
                'location' => 'Ikeja',
                'agent' => 'folasade.adeyemi@primelandng.com',
                'featured' => false,
                'description' => 'Compact, well-finished 1 bedroom apartment close to the Ikeja business district, ideal for young professionals.',
            ],
            [
                'title' => 'Residential Land in Gated Estate',
                'listing_type' => 'sale',
                'property_type' => 'Land',
                'price' => 65000000,
                'bedrooms' => null,
                'bathrooms' => null,
                'toilets' => null,
                'parking_spaces' => null,
                'area_sqm' => 650,
                'address' => 'Golf Estate Extension, Gwarinpa',
                'location' => 'Gwarinpa',
                'agent' => 'emeka.umeh@gwarinparealty.ng',
                'featured' => false,
                'description' => 'Dry, fenced residential plot with a governor\'s consent title, located in a secure gated estate.',
            ],
            [
                'title' => '5 Bedroom Detached House for Rent',
                'listing_type' => 'rent',
                'property_type' => 'Detached House',
                'price' => 12000000,
                'bedrooms' => 5,
                'bathrooms' => 5,
                'toilets' => 6,
                'parking_spaces' => 3,
                'area_sqm' => 520,
                'address' => 'Yedseram Street, Maitama',
                'location' => 'Maitama',
                'agent' => 'tunde.bakare@capitalliving.ng',
                'featured' => true,
                'description' => 'An executive 5 bedroom home with a study and staff quarters, ideal for diplomatic or corporate lets. Annual rent.',
            ],
            [
                'title' => 'Studio Shortlet Apartment',
                'listing_type' => 'shortlet',
                'property_type' => 'Apartment',
                'price' => 45000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'toilets' => 1,
                'parking_spaces' => 1,
                'area_sqm' => 45,
                'address' => 'Herbert Macaulay Way, Port Harcourt GRA',
                'location' => 'Port Harcourt GRA',
                'agent' => 'ibinabo.wokoma@harborline.ng',
                'featured' => false,
                'description' => 'Cosy studio apartment with fast Wi-Fi and a dedicated workspace, popular with short-term corporate visitors. Priced per night.',
            ],
            [
                'title' => 'Mixed-Use Commercial Plot',
                'listing_type' => 'sale',
                'property_type' => 'Land',
                'price' => 180000000,
                'bedrooms' => null,
                'bathrooms' => null,
                'toilets' => null,
                'parking_spaces' => null,
                'area_sqm' => 1200,
                'address' => 'Obafemi Awolowo Way, Ikeja',
                'location' => 'Ikeja',
                'agent' => 'folasade.adeyemi@primelandng.com',
                'featured' => false,
                'description' => 'Corner-piece commercial land approved for mixed-use development, fronting a major arterial road.',
            ],
            [
                'title' => '4 Bedroom Terrace Duplex for Rent',
                'listing_type' => 'rent',
                'property_type' => 'Duplex',
                'price' => 6500000,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'toilets' => 5,
                'parking_spaces' => 2,
                'area_sqm' => 280,
                'address' => 'Chevron Drive, Lekki',
                'location' => 'Lekki',
                'agent' => 'chiamaka.nwosu@lekkishores.ng',
                'featured' => false,
                'description' => 'Modern terrace duplex within a serviced estate offering a gym, pool, and 24-hour security. Annual rent.',
            ],
            [
                'title' => 'Waterfront 3 Bedroom Shortlet',
                'listing_type' => 'shortlet',
                'property_type' => 'Apartment',
                'price' => 150000,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'toilets' => 4,
                'parking_spaces' => 2,
                'area_sqm' => 180,
                'address' => 'Kingsway Road, Ikoyi',
                'location' => 'Ikoyi',
                'agent' => 'adaeze.okafor@summitestates.ng',
                'featured' => true,
                'description' => 'A premium waterfront shortlet apartment with panoramic lagoon views, ideal for executive stays. Priced per night.',
            ],
        ];

        foreach ($listings as $listing) {
            $location = Location::where('name', $listing['location'])->first();
            $agent = Agent::where('email', $listing['agent'])->first();

            Listing::firstOrCreate(
                ['slug' => Str::slug($listing['title'])],
                [
                    'title' => $listing['title'],
                    'listing_type' => $listing['listing_type'],
                    'property_type' => $listing['property_type'],
                    'price' => $listing['price'],
                    'bedrooms' => $listing['bedrooms'],
                    'bathrooms' => $listing['bathrooms'],
                    'toilets' => $listing['toilets'],
                    'parking_spaces' => $listing['parking_spaces'],
                    'area_sqm' => $listing['area_sqm'],
                    'address' => $listing['address'],
                    'location_id' => $location?->id,
                    'agent_id' => $agent?->id,
                    'status' => 'active',
                    'featured' => $listing['featured'],
                    'description' => $listing['description'],
                ]
            );
        }
    }
}
